project:
  type: website
  output-dir: build

website:
  title: "TravelHunters - Documentation"
  search: true
  navbar:
    background: primary
    title: "TravelHunters"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Project Charter"
        file: project_charta.qmd
      - text: "Data Report"
        file: data_report.qmd
      - text: "Modelling"
        file: modelling_report.qmd
      - text: "Evaluation"
        file: evaluation.qmd
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Project Overview"
        contents:
          - index.qmd
          - project_charta.qmd
      - section: "Data & Modelling"
        contents:
          - data_report.qmd
          - modelling_report.qmd
      - section: "Evaluation & Deployment"
        contents:
          - evaluation.qmd
          

bibliography: refs.bib
csl: vancouver-brackets.csl

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
  
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
    colorlinks: true

jupyter: python3

execute:
  freeze: auto
  echo: true
  warning: false
  error: false

editor:
  render-on-save: true